<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>To-Do App</title>
        <link href="https://fonts.googleapis.com/css?family=Homemade+Apple|Permanent+Marker&display=swap" rel="stylesheet">
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='/css/style.css' rel='stylesheet' type='text/css'>
        <script type="text/javascript" src="index.js" defer></script>
    </head>
    <body id="body">
    <h1 class="headline">To-Do List</h1>
    <div id="title">

    </div>
    <div id="content" class="content">
        <ul id="list">
        </ul>
    </div>
    </body>
</html>
